-------------------------------------------------------------------------------
Test set: com.redhat.internal.config.RunnerTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 1.819 s <<< FAILURE! - in com.redhat.internal.config.RunnerTest
1  Time elapsed: 1.422 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (2 failures)
	io.cucumber.core.exception.CucumberException: Could not invoke hook defined at 'com.redhat.internal.cases.CSSteps.beforTest(io.cucumber.java.Scenario)'.
It appears there was a problem with the hook definition.
	io.cucumber.core.exception.CucumberException: Could not invoke hook defined at 'com.redhat.internal.cases.CSSteps.afterTest(io.cucumber.java.Scenario)'.
It appears there was a problem with the hook definition.

2  Time elapsed: 0.046 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (2 failures)
	io.cucumber.core.exception.CucumberException: Could not invoke hook defined at 'com.redhat.internal.cases.CSSteps.beforTest(io.cucumber.java.Scenario)'.
It appears there was a problem with the hook definition.
	io.cucumber.core.exception.CucumberException: Could not invoke hook defined at 'com.redhat.internal.cases.CSSteps.afterTest(io.cucumber.java.Scenario)'.
It appears there was a problem with the hook definition.

3  Time elapsed: 0.038 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (2 failures)
	io.cucumber.core.exception.CucumberException: Could not invoke hook defined at 'com.redhat.internal.cases.CSSteps.beforTest(io.cucumber.java.Scenario)'.
It appears there was a problem with the hook definition.
	io.cucumber.core.exception.CucumberException: Could not invoke hook defined at 'com.redhat.internal.cases.CSSteps.afterTest(io.cucumber.java.Scenario)'.
It appears there was a problem with the hook definition.

